## **Car Prediction Project | Training Model**
1. Import Data
2. import preprocessing pipeline
3. Splitting Data
4. Data Scaling
5. Feature Selection
6. Linear ML Model

In [ ]:
import pandas as pd
import Data_Preprocessing as dp
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression 
from sklearn.ensemble import RandomForestRegressor 
from sklearn.metrics import mean_squared_error , r2_score

In [ ]:
data = pd.read_csv("car_price_prediction.csv")
data.head(5)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12
1,44731507,16621,1018,CHEVROLET,Equinox,2011,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8
2,45774419,8467,-,HONDA,FIT,2006,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2
3,45769185,3607,862,FORD,Escape,2011,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0
4,45809263,11726,446,HONDA,FIT,2014,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4

In [ ]:
data = dp.preprocessing_pipeline(data)

Starting Processing..............
Shape Before processing = (19237, 18)
Replacing Categorical Values.............
Feature Engineering within Categorical Values.............
Before deleting outliers Shape = (19237, 25)
After deleting outliers Shape = (10463, 25)
Feature Engineering within Numerical Values...........
Dropping Columns.......
Shape After processing = (10463, 22)

In [ ]:
data.head(5)

,Price,Levy,Manufacturer,Model,Category,Fuel type,Engine volume,Mileage,Color,Airbags,...,Gear box type_Automatic,Gear box type_Manual,Gear box type_Tiptronic,Gear box type_Variator,Drive wheels_4x4,Drive wheels_Front,Drive wheels_Rear,Wheel_Left wheel,Wheel_Right-hand drive,Age
2,8467,0,21,684,3,5,1.3,200000,1,2,...,False,False,False,True,False,True,False,False,True,20
3,3607,862,16,661,4,2,2.5,168966,14,0,...,True,False,False,False,True,False,False,True,False,15
4,11726,446,21,684,3,5,1.3,91901,12,4,...,True,False,False,False,False,True,False,True,False,12
5,39493,891,23,1305,4,1,2.0,160931,14,4,...,True,False,False,False,False,True,False,True,False,10
6,1803,761,58,1154,3,2,1.8,258909,14,12,...,True,False,False,False,False,True,False,True,False,16

In [ ]:
y = data["Price"]
X = data.drop(["Price"], inplace=False, axis=1)

In [ ]:
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.3, random_state=42
)
X_validation, X_test, y_validation, y_test = train_test_split(
    X_temp, y_temp, test_size=0.5, random_state=42
)

print(f"Train Set: {len(X_train)} Samples")  # 70%
print(f"Validation Set: {len(X_validation)} Samples")  # 15%
print(f"Test Set: {len(X_test)} Samples")  # 15%
print(f"Train Set Percentage: {round((len(X_train)/len(X))*100,4)}%")  # 70%
print(f"Validation Set Percentage: {round((len(X_validation)/len(X))*100,4)}%")  # 15%
print(f"Test Set Percentage: {round((len(X_test)/len(X))*100,4)}%")  # 15%

Train Set: 7324 Samples
Validation Set: 1569 Samples
Test Set: 1570 Samples
Train Set Percentage: 69.999%
Validation Set Percentage: 14.9957%
Test Set Percentage: 15.0053%

In [ ]:
train = pd.concat([X_train, y_train], axis=1)
for cols in ["Fuel type", "Model", "Airbags", "Manufacturer"]:
    mean_encoded = train.groupby(cols)["Price"].mean()
    global_mean = train["Price"].mean()
    X_train[cols] = X_train[cols].map(mean_encoded).fillna(global_mean)
    X_validation[cols] = X_validation[cols].map(mean_encoded).fillna(global_mean)
    X_temp[cols] = X_temp[cols].map(mean_encoded).fillna(global_mean)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_validation = scaler.transform(X_validation)
X_temp = scaler.transform(X_temp)

In [ ]:
LRModel = LinearRegression()
LRModel.fit(X=X_train, y=y_train)

LinearRegression()

In [ ]:
y_predict = LRModel.predict(X_validation)
rmse = mean_squared_error(y_validation, y_predict)
r2 = r2_score(y_validation,y_predict)

print(f"Root Mean Squared Value: {rmse}")
print(f"R^2 : {r2}")

Root Mean Squared Value: 61750484.99184735
R^2 : 0.5525398336365108

In [ ]:
RFModel = RandomForestRegressor()
RFModel.fit(X_train , y_train)

RandomForestRegressor()

In [ ]:
y_predict = RFModel.predict(X_validation)
rmse = mean_squared_error(y_validation, y_predict)
r2 = r2_score(y_validation,y_predict)

print(f"Root Mean Squared Value: {rmse}")
print(f"R^2 : {r2}")

Root Mean Squared Value: 28981838.17614224
R^2 : 0.7899900197783309